// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkIzQgvAyvTBQZS7dOKXstfJcnR6zxcuk',
    appId: '1:723230534177:web:f881c8b665f2aa8ec15160',
    messagingSenderId: '723230534177',
    projectId: 'usuarioselbuho',
    authDomain: 'usuarioselbuho.firebaseapp.com',
    storageBucket: 'usuarioselbuho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ-U1vOwV7nbUC35GMLTqgiY3qway81y0',
    appId: '1:723230534177:android:c96e2d2808985fa0c15160',
    messagingSenderId: '723230534177',
    projectId: 'usuarioselbuho',
    storageBucket: 'usuarioselbuho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTlEFo6j2i4vUscxYAiP0uLUuqRmAOMQ',
    appId: '1:530766705461:ios:0b3f45cc738c4cea6f527c',
    messagingSenderId: '530766705461',
    projectId: 'mi-app-turismo',
    storageBucket: 'mi-app-turismo.firebasestorage.app',
    iosBundleId: 'com.example.appturistica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTlEFo6j2i4vUscxYAiP0uLUuqRmAOMQ',
    appId: '1:530766705461:ios:0b3f45cc738c4cea6f527c',
    messagingSenderId: '530766705461',
    projectId: 'mi-app-turismo',
    storageBucket: 'mi-app-turismo.firebasestorage.app',
    iosBundleId: 'com.example.appturistica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYUM4itWjBcVIWChGKH-WhJoVeTKXVL2M',
    appId: '1:530766705461:web:24b05a3ff2d532cf6f527c',
    messagingSenderId: '530766705461',
    projectId: 'mi-app-turismo',
    authDomain: 'mi-app-turismo.firebaseapp.com',
    storageBucket: 'mi-app-turismo.firebasestorage.app',
  );

}